version: '3.7'
services:
    postgres:
        build: docker-image/postgres/
        image: code-walg-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        volumes:
        - ./volumes/postgres/:/var/lib/postgresql/data/

    walg:
        build: docker-image/wal-g/
        image: code-walg
        entrypoint: sleep 100d
        environment:
            PGHOST: postgres
            PGUSER: postgres
            PGPASSWORD: password
            AWS_ACCESS_KEY_ID: "admin"
            AWS_SECRET_ACCESS_KEY: "password"
            WALE_S3_PREFIX: "s3://walg/backup"
            AWS_ENDPOINT: "http://s3:9000"
            AWS_S3_FORCE_PATH_STYLE: "true"
            AWS_REGION: us-east-1
            WALG_COMPRESSION_METHOD: brotli
        volumes:
            - ./src/:/go/
            - ./volumes/postgres/:/var/lib/postgresql/data/
    
    s3:
        image: minio/minio:RELEASE.2020-03-25T07-03-04Z
        environment:
            MINIO_ACCESS_KEY: admin
            MINIO_SECRET_KEY: password
        ports:
        - "9000:9000"
        volumes:
            - ./volumes/minio/:/data
        entrypoint: sh
        command: >
            -c 'mkdir -p /data/walg
            && /usr/bin/minio server /data'
        